/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,ts,scss}",
    "./src/**/*.component.html",
    "./src/**/*.component.ts"
  ],
  theme: {
    extend: {
      colors: {
        // Custom brand colors that align with the button system
        'brand-orange': '#fc7900',
        'brand-orange-hover': '#e66a00',
        'brand-blue': '#0226ff',
        'brand-blue-hover': '#0119b3',
        'brand-blue-light': '#3b82f6',
        'brand-blue-light-hover': '#2563eb',
        'brand-cyan': '#06b6d4',
        'brand-cyan-hover': '#0891b2',
        'brand-white': '#ffffff',
        'brand-gray': '#6b7280',
        'brand-gray-hover': '#4b5563',
        // Add standard Tailwind orange colors for theme() function
        orange: {
          50: '#fff7ed',
          100: '#ffedd5',
          200: '#fed7aa',
          300: '#fdba74',
          400: '#fb923c',
          500: '#f97316',
          600: '#ea580c',
          700: '#c2410c',
          800: '#9a3412',
          900: '#7c2d12'
        }
      },
      fontFamily: {
        // Since no Google Fonts are detected, using system fonts for optimal performance
        'sans': ['system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif']
      }
    }
  },
  plugins: [],
  // Safelist common utility classes to avoid purging issues
  safelist: [
    'bg-white',
    'px-2',
    'px-4',
    'py-2',
    'text-white',
    'text-gray-800',
    'text-gray-600',
    'bg-gray-100',
    'bg-gray-200',
    'bg-gray-50',
    'border',
    'border-gray-300',
    'border-gray-200',
    'rounded',
    'rounded-lg',
    'shadow',
    'shadow-md',
    'flex',
    'items-center',
    'justify-center',
    'justify-between',
    'space-x-2',
    'space-x-4',
    'space-y-2',
    'space-y-4',
    'space-y-6',
    'w-full',
    'w-4',
    'w-5',
    'w-8',
    'h-full',
    'h-4',
    'h-5',
    'h-8',
    'max-w-md',
    'max-w-lg',
    'max-w-xl',
    'max-w-2xl',
    'container',
    'mx-auto',
    'p-4',
    'p-6',
    'p-8',
    'm-4',
    'm-6',
    'm-8',
    'mt-4',
    'mt-1',
    'mb-4',
    'mb-2',
    'mb-6',
    'ml-4',
    'ml-2',
    'ml-3',
    'mr-4',
    'mr-2',
    'mr-1',
    'text-sm',
    'text-xs',
    'text-base',
    'text-lg',
    'text-xl',
    'text-2xl',
    'text-3xl',
    'font-medium',
    'font-semibold',
    'font-bold',
    'text-gray-700',
    'text-gray-500',
    'text-gray-400',
    'text-red-600',
    'text-red-700',
    'text-green-600',
    'text-blue-600',
    'text-yellow-800',
    'text-green-800',
    'text-red-800',
    'text-orange-600',
    'bg-orange-600',
    'bg-orange-700',
    'bg-orange-50',
    'bg-orange-100',
    'bg-red-50',
    'bg-red-100',
    'bg-red-200',
    'bg-red-600',
    'bg-red-700',
    'bg-green-50',
    'bg-green-100',
    'bg-green-200',
    'bg-yellow-100',
    'bg-blue-50',
    'border-red-300',
    'border-red-200',
    'border-green-200',
    'border-orange-400',
    'border-gray-200',
    'border-transparent',
    'hover:bg-gray-50',
    'hover:bg-orange-700',
    'hover:bg-red-700',
    'hover:bg-red-50',
    'hover:bg-red-200',
    'hover:bg-green-200',
    'hover:bg-yellow-200',
    'hover:text-indigo-600',
    'hover:text-red-500',
    'focus:outline-none',
    'focus:ring-2',
    'focus:ring-offset-2',
    'focus:ring-indigo-500',
    'focus:ring-orange-500',
    'focus:ring-red-500',
    'focus:border-orange-500',
    'focus:border-red-500',
    'transition',
    'transition-colors',
    'transition-all',
    'duration-200',
    'duration-300',
    'ease-in-out',
    'ease-out',
    'animate-spin',
    'cursor-not-allowed',
    'cursor-move',
    'opacity-50',
    'opacity-30',
    'disabled:opacity-50',
    'disabled:cursor-not-allowed',
    'aspect-square',
    'object-cover',
    'overflow-hidden',
    'resize',
    'resize-none',
    'resize-x',
    'resize-y',
    'grid',
    'grid-cols-1',
    'grid-cols-2',
    'grid-cols-3',
    'gap-6',
    'lg:grid-cols-2',
    'lg:grid-cols-3',
    'relative',
    'absolute',
    'inset-y-0',
    'left-0',
    'pointer-events-none',
    'flex-shrink-0',
    'inline-flex',
    'block',
    'truncate',
    'pt-6',
    'pl-3',
    'pl-7'
  ]
};